// <auto-generated />
using System;
using AutoMapper.Samples.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapper.Samples.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoMapper.Samples.Models.AuthorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Alexandre",
                            LastName = "Castro"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Martin",
                            LastName = "Fowler"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Gang",
                            LastName = "Of Four"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Christophe",
                            LastName = "Mommer"
                        });
                });

            modelBuilder.Entity("AutoMapper.Samples.Models.BookModel", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int?>("AuthorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            BookTitle = "AutoMapper samples"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            BookTitle = "Clean Code"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3,
                            BookTitle = "Design patterns"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4,
                            BookTitle = "Docker pour les développeurs .Net"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 4,
                            BookTitle = "Blazor :développement front end d'application web dynamiques"
                        });
                });

            modelBuilder.Entity("AutoMapper.Samples.Models.BookModel", b =>
                {
                    b.HasOne("AutoMapper.Samples.Models.AuthorModel", "Author")
                        .WithMany("BooksCollection")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AutoMapper.Samples.Models.AuthorModel", b =>
                {
                    b.Navigation("BooksCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
